# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-14 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabe_app', '0002_auto_20200214_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='failure_url',
            field=models.CharField(default='response', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='success_url',
            field=models.CharField(default='response', max_length=255),
            preserve_default=False,
        ),
    ]
