# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-22 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabe_app', '0003_auto_20200214_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='knet',
            field=models.CharField(choices=[('Enabaled', 'Enabaled'), ('Disabled', 'Disabled')], default='Enabaled', max_length=50, verbose_name='Knet Staus'),
        ),
        migrations.AddField(
            model_name='credential',
            name='mpgs',
            field=models.CharField(choices=[('Enabaled', 'Enabaled'), ('Disabled', 'Disabled')], default='Disabled', max_length=50, verbose_name='Mpgs Staus'),
        ),
    ]
