# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-27 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabe_app', '0004_auto_20200222_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='payment_url',
            field=models.CharField(default='fdgdg', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='knet',
            field=models.CharField(choices=[('Enabaled', True), ('Disabled', False)], default='Enabaled', max_length=50, verbose_name='Knet Staus'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='mpgs',
            field=models.CharField(choices=[('Enabaled', True), ('Disabled', False)], default='Disabled', max_length=50, verbose_name='Mpgs Staus'),
        ),
    ]
