# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-27 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabe_app', '0006_auto_20200227_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='knet',
            field=models.CharField(choices=[('Enabled', True), ('Disabled', False)], default='Enabaled', max_length=50, verbose_name='Knet Staus'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='mpgs',
            field=models.CharField(choices=[('Enabled', True), ('Disabled', False)], default='Disabled', max_length=50, verbose_name='Mpgs Staus'),
        ),
    ]
