# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-07 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabe_app', '0012_auto_20200307_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='accesscode',
            field=models.CharField(default='0', max_length=255, verbose_name='Access Code'),
        ),
    ]
