# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabe_app', '0013_credential_accesscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='knet',
            field=models.BooleanField(choices=[(True, 'Enable'), (False, 'Disable')], default='Enabaled', max_length=50, verbose_name='KNET Staus'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='merchant_code',
            field=models.IntegerField(max_length=45, verbose_name='Merchant Code'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='mpgs',
            field=models.BooleanField(choices=[(True, 'Enable'), (False, 'Disable')], default='Disabled', max_length=50, verbose_name='MPGS Staus'),
        ),
    ]
